---
- name: Create directories
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/venvs/"
    mode: "0775"
    state: directory

- name: Install dependencies
  ansible.builtin.apt:
    name:
      # apt_repository module
      - python3-apt
      - gpg
      # Molecule
      - python3-pip
      - libssl-dev
    state: present
    update_cache: true
  become: true

- name: Add python repo
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present
  become: true

- name: Install python3.10
  ansible.builtin.apt:
    name: python3.10
    state: present
  become: true

- name: Set python3.10 as default
  community.general.alternatives:
    name: python
    path: /usr/bin/python3.10
    link: /usr/bin/python
    state: selected
  become: true

- name: Install venv package
  ansible.builtin.pip:
    name: virtualenv
    state: present
  become: true

- name: Uninstall packages in venv
  ansible.builtin.pip:
    name:
      - molecule-docker
      - molecule-vagrant
    state: absent
    virtualenv: "{{ ansible_facts['user_dir'] }}/venvs/molecule"
    virtualenv_python: python3.10

- name: Install packages in venv
  ansible.builtin.pip:
    name:
      - molecule==5.*
      - ansible-core
      - ansible-lint
      - molecule-plugins[docker]
      - molecule-plugins[vagrant]
    state: present
    virtualenv: "{{ ansible_facts['user_dir'] }}/venvs/molecule"
    virtualenv_python: python3.10
